{% set name = "stackvana-afw" %}
# LSST DM versions are prefixed with letters
#
#  - a weekly build is 'w_2018_50'
#  - a major release is 'v18_1'
#
# In order to play nice with conda, we take the following conventions
#
#  - for a weekly build 'w_2018_50', the conda version is '0.2018.50'
#  - for a major version 'v18_1', the conda version is '18.1.0'
#
{% set version = "0.2023.20" %}
{% set patch_version = version.split(".")[-1] if version.split(".")[-1].__len__() == 2 else "0" + version.split(".")[-1] %}
{% set dm_tag = "w_" + version.split(".")[1] + "_" + patch_version if version.startswith("0.") else "v" + version.replace(".", "_") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://eups.lsst.codes/stack/src/tags/{{ dm_tag }}.list
  sha256: 73d435c4573c03fd6b440d7f9ab89424098c2b373554746319fd48767445a364

build:
  skip: true  # [win or py != 310]
  number: 0
  merge_build_host: true
  script:
    - stackvana-build afw

requirements:
  host:
    - stackvana-core =={{ version }}
    - python
  run:
    - python
    - stackvana-core =={{ version }}

test:
  commands:
    - setup afw
    - python -c "import lsst.afw"

about:
  home: https://github.com/beckermr/stackvana-core
  license: GPL-3.0-or-later
  license_family: GPL
  license_file:
    - LICENSE
    - COPYRIGHT
  summary: stackvana build up to afw

extra:
  recipe-maintainers:
    - beckermr
